### ISSUE TITLE
The 0.8.0 release tag fails to install

### ISSUE THREAD

**Issue by aOelschlager** [Islandora-Devops/islandora-starter-site#111]
The error:
  - Installing islandora/advanced_search (2.0.0-beta3): Cloning 2.0.0-beta3
    2.0.0-beta3 is gone (history was rewritten?)
   
The url [here](https://github.com/Islandora-Devops/islandora-starter-site/blob/0d222ca525dc9e1e562ab6e13e46f27a6dd9374b/composer.json#L35) needs to be changed to https://github.com/islandora/advanced_search and the lock file would need to be updated. 

Those changes do fix the error but since it's a tagged release can a pr be done? Would an alternative be making a branch to pull from instead?

**Comment by rosiel** [comment]
From the [Composer docs](https://getcomposer.org/doc/05-repositories.md#package-2), 

> This ['package'] repository type has a few limitations and should be avoided whenever possible.

For that reason, we've already moved away from it. However, not coming up at all on 0.8.0 is a problem.

<img width="781" alt="Screenshot 2023-09-13 at 1 29 33 PM" src="https://github.com/Islandora-Devops/islandora-starter-site/assets/1943338/b2f9db86-72d6-467e-a795-74af763dc34f">

Maybe just a lock file update would make it work. I'm not sure what to do about branches since we're now supposed to be on Drupal 10 (and some of that isn't working right now). It's unclear to me what to focus on and what to deliver (e.g. are we going to start a new branch for updates to drupal 9?).

**Comment by rosiel** [comment]
OH I found the problem.

When we transfered over digitalutsc/advanced_search to islandora/advanced_search, Github put in a redirect so that they'd resolve.

Now there is a new repo at https://github.com/digitalutsc/advanced_search/ and it does not have the required tags.

**Comment by rosiel** [comment]
@kstapelfeldt @Natkeeran @kylehuynh205  If you could push the 2.0.0-beta3 tag to your fork of advanced_search, then we'd still be able to run the (legacy but still used/useful) starter site version that uses Drupal 9.

**Comment by kylehuynh205** [comment]
Hi @rosiel , the tag 2.0.0-beta3 has been pushed. https://github.com/digitalutsc/advanced_search/tags.
